export const SORT_TYPE = ["ASC", "DESC", ""];

export const FIELD_SORT_LIST_IN_GET_USERS = ["USER_NAME", "USER_LAST_NAME", "USER_FIRST_NAME"];
export const FIELD_SORT_LIST_IN_GET_SHOPS = ["SHOP_NAME", "SHOP_ADDRESS", "SHOP_PHONE"];
